title: Everyday Econ
name: Max Liu
description: >-
  Simple economic insights for daily life.
url: "https://everydayecon.github.io"
baseurl: "" 
repository: everydayecon/everydayecon.github.io
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/
locale: "en-US"
markdown: kramdown
highlighter: rouge

author:
  name: Max Liu
  avatar: "/assets/images/avatar.png"
  bio: "Economics explained simply."
  location: "Washington, DC"
  email: max@example.com

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Navigation bar
header:
  pages:
    - title: Home
      url: /
    - title: Categories
      url: /categories/
    - title: About
      url: /about/

include: ["_pages"]